### ISSUE TITLE
Health listener does not fire when loading save

### ISSUE THREAD

**Issue by Necavi** [matzman666/PyPipboy#1]
I've been using the stimpack example script and it seems to stop working any time I die/load a save.

I would assume that the health change event would trigger in the event of a load, but if not is there another event that does fire by any chance?

**Comment by matzman666** [comment]
Whenever a new game is loaded, all values beneath the "PlayerInfo" object get invalidated, and a new "CurrHP" value is created. You need to register a valueChanged listener to the "PlayerInfo" object, and when it gets executed, you then fetch the new "CurrHP" value. This is the case with most values, they get invalidated when loading a new savegame. You need to register valueChanged listeners to their parents (or parent's parents). I still haven't found out which exact values persist a savegame load, and which don't, you need to experiment a bit. I will update the documentation in the next days.

**Comment by Necavi** [comment]
Excellent, thanks!
